version: "3.9"

services:

  workerdisk:

    build: .

    environment:

      - ID=${ID}

      - HASH=${HASH}

      - TOKEN=${TOKEN}

    # Expose port 8080 for the container to listen on

    EXPOSE 8080

